// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorChoreList.Data;

#nullable disable

namespace RazorChoreList.Migrations
{
    [DbContext(typeof(RazorChoreListContext))]
    partial class RazorChoreListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Chore", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChoreDoer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoreName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionStatus")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Chore");
                });
#pragma warning restore 612, 618
        }
    }
}
